language: java
jdk: openjdk11

before_install:
  # Checkout master branch not commit on master builds
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    git checkout $TRAVIS_BRANCH;
    fi
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - mvn fmt:check
  - export TZ=Europe/London

script:
  - mvn test -B
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - git config --global user.email "travis@travis-ci.org";
  - git config --global user.name "Travis CI";
  - echo -n "$GITHUB_DEPLOY_KEY" | base64 -d > /home/travis/.ssh/id_rsa
  - echo "Host github.com" > ~/.ssh/config 
  - echo "Hostname github.com" >> ~/.ssh/config 
  - echo "User git" >> ~/.ssh/config 
  - echo "PubkeyAuthentication yes" >> ~/.ssh/config 
  - echo "IdentityFile /home/travis/.ssh/id_rsa" >> ~/.ssh/config 
  - chmod 600 /home/travis/.ssh/id_rsa > ~/.ssh/config 
  - if [ "$BRANCH" == "master" ]; then
     if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      mvn -B release:prepare;
      mvn -B release:perform;
     fi
    else
      mvn deploy;
    fi

cache:
  directories:
  - $HOME/.m2

