language: java
jdk: openjdk8

before_install: cp .travis.settings.xml $HOME/.m2/settings.xml

notifications:
  slack:
    rooms:
      secure: Ej8YfbNt53/hxswHVcfQAvVcVvWMFG2qkErQCQf8sGNcGR3adx2r5cHvKGuXARQtsKzd4S8Kw68cLR1htnaKMsI1AY3aa8yC++WOdqmbcvY/daZgmz2gU8sAidSS4eJ68AhMj29nFViw/3DgLlaf8apMIzhvxEvuI6FkvjNs5Y7O4rBFhYWAa2T28GXRhMuLwBZ0yiDXdmmZdp4CNVWEk4eOnDm6cQ/2UxbCPuNngYXANKE5W4cMA/pIfq2ahrOvQFYgLW9AfhiYRrO3Ijh7fNSv3neyaIIuOVC/5xKGPiCYWwT8gqAqh3Cqq1TLcXce5WBI3H6mbdfM1MTtfn5cOwvIJU2S/zSOKhdRPCaUQuf1kwc+ldRHfeBQ+xwRfYQQ4GXiFT1z6mzvKrNI/pUdI+VCEddw8EeX/lDrTLIR4aQ+04glIJOrJRjTvqur6QbHYnnHPSADGLczt6oPQyHeh+fKMeNAuv+cGO8FbmF7GzEFmDDdWP0stlWgk+75534NDS33ojsnrhYj3GvRmRIFRpntJVcAr0W8mupi10RQ9XkOuEQVKkSuRBJVEXYJ0e4D3PqjPs4hECLyB3ZlNw+t486fELKK+qWWy+7voxzPDEaxY0OvFRhkOPLTezFpOhU82uckPI/5QAFngQqNFJ5OCL795bmQRXqtSM+pj/XwC7U=
    on_failure: always
    on_success: never

cache:
  directories:
  - $HOME/.m2

branches:
    only:
        - master